openapi: 3.0.1
info:
  title: Enseada
  description: A Cloud native multi-package registry
  contact:
    email: enseada@pm.me
    url: https://enseada.io
  license:
    name: MPL 2.0
    url: https://opensource.org/licenses/MPL-2.0
  version: 0.1.0
externalDocs:
  description: Find out more about Enseada
  url: https://enseada.io
tags:
  - name: users
    description: User management endpoints
  - name: maven
    description: Maven registry endpoints
  - name: docker
    description: Docker V2 registry endpoints
  - name: monitoring
    description: Monitoring and observability endpoints
paths:
  /api/v1/users/me:
    get:
      tags:
        - users
      summary: Fetches information about the currently authenticated user
      operationId: user::me
      security:
        - oauth:
            - profile
      responses:
        200:
          description: Current user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
  /api/v1/users/register:
    post:
      tags:
        - users
      summary: Register a new user
      operationId: user::register
      security:
        - oauth:
            - users:manage
      requestBody:
        required: true
        description: New user login information
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserRegistrationForm'
      responses:
        200:
          description: New user information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
  /health:
    get:
      tags:
        - monitoring
      summary: Get the server health status
      operationId: health::get
      responses:
        200:
          description: Server is active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        503:
          description: Server is not active
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/APIError'
components:
  schemas:
    MeResponse:
      type: object
      required:
        - username
      properties:
        username:
          type: string
    UserRegistrationForm:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: ['ok']
    APIError:
      type: object
      required:
        - errors
      properties:
        errors:
          type: array
          items:
            type: string
          example: ['an error has occurred']
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth/authorize
          tokenUrl: /oauth/token
          scopes:
            profile: access user profile information
            users:read: read-only access to registered users
            users:manage: read-write access to registered users
