name: Check Pull Request

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1-buster
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: target/debug
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}{1}', github.workspace, '/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install build-essential libssl-dev llvm-dev libclang-dev -y
          rustup update
          rustup component add clippy
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          npm --version || true
          yarn --version || true
          yarn install --frozen-lockfile
      - name: Lint code
        run: |
        #          Reenable when issues are fixed
      #          cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: |
          cargo test
