name: Master

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: golang:1.13-alpine
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.os }}-go-${{ hashFiles(format('{0}{1}', github.workspace, '/go.sum')) }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Install Dependencies
        run: |
          go mod vendor
      - name: Lint code
        run: |
          go vet ./...
          go build -o /dev/null ./...
      - name: Run tests
        run: |
          go test ./...
  protocols-check:
    runs-on: ubuntu-latest
      container:
        image: uber/prototool:1.8.1
      steps:
        - uses: actions/checkout@v1
        - name: Check protocols
          run: |
            prototool files ./rpc
            prototool compile ./rpc
            prototool lint ./rpc
            prototool break check ./rpc --git-branch master