name: Master

on:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container:
      image: rust:1-buster
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: target/debug
          key: ${{ runner.os }}-cargo-${{ hashFiles(format('{0}{1}', github.workspace, '/Cargo.lock')) }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Install Dependencies
        run: |
          RUN apt-get update -y && apt-get install build-essential libssl-dev llvm-dev libclang-dev -y
          rustup update
          rustup component add clippy
      - name: Lint code
        run: |
          cargo clippy --all-targets --all-features -- -D warnings
      - name: Run tests
        run: |
          cargo test